package com.pettopia.model.bean;
// Generated Mar 21, 2018 11:04:53 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int userid;
     private String userfname;
     private String userlname;
     private Date userbirthdate;
     private String userpassword;
     private String userjob;
     private String useremail;
     private long usercreditnumber;
     private long usercreditlimit;
     private String useraddress;

    public User() {
    }

	
    public User(int userid) {
        this.userid = userid;
    }
    public User(int userid, String userfname, String userlname, Date userbirthdate, String userpassword, String userjob, String useremail, long usercreditnumber, long usercreditlimit, String useraddress) {
       this.userid = userid;
       this.userfname = userfname;
       this.userlname = userlname;
       this.userbirthdate = userbirthdate;
       this.userpassword = userpassword;
       this.userjob = userjob;
       this.useremail = useremail;
       this.usercreditnumber = usercreditnumber;
       this.usercreditlimit = usercreditlimit;
       this.useraddress = useraddress;
    }
   
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }
    public String getUserfname() {
        return this.userfname;
    }
    
    public void setUserfname(String userfname) {
        this.userfname = userfname;
    }
    public String getUserlname() {
        return this.userlname;
    }
    
    public void setUserlname(String userlname) {
        this.userlname = userlname;
    }
    public Date getUserbirthdate() {
        return this.userbirthdate;
    }
    
    public void setUserbirthdate(Date userbirthdate) {
        this.userbirthdate = userbirthdate;
    }
    public String getUserpassword() {
        return this.userpassword;
    }
    
    public void setUserpassword(String userpassword) {
        this.userpassword = userpassword;
    }
    public String getUserjob() {
        return this.userjob;
    }
    
    public void setUserjob(String userjob) {
        this.userjob = userjob;
    }
    public String getUseremail() {
        return this.useremail;
    }
    
    public void setUseremail(String useremail) {
        this.useremail = useremail;
    }
    public long getUsercreditnumber() {
        return this.usercreditnumber;
    }
    
    public void setUsercreditnumber(long usercreditnumber) {
        this.usercreditnumber = usercreditnumber;
    }
    public long getUsercreditlimit() {
        return this.usercreditlimit;
    }
    
    public void setUsercreditlimit(long usercreditlimit) {
        this.usercreditlimit = usercreditlimit;
    }
    public String getUseraddress() {
        return this.useraddress;
    }
    
    public void setUseraddress(String useraddress) {
        this.useraddress = useraddress;
    }




}


